{
  "Header": {
    "Original": "CVE-2018-20721 (URI_FUNC() in UriParse.c in uriparser before 0.9.1 has an out-of-bound ...)",
    "Line": 303248,
    "ID": "CVE-2018-20721",
    "Description": "(URI_FUNC() in UriParse.c in uriparser before 0.9.1 has an out-of-bound ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2834-1 DLA-1682-1}",
      "Line": 303249,
      "Type": "xref",
      "Bugs": [
        "DLA-2834-1",
        "DLA-1682-1"
      ]
    },
    {
      "Original": "- uriparser 0.9.1-1 (low)",
      "Line": 303250,
      "Type": "package",
      "Package": "uriparser",
      "Kind": "fixed",
      "Version": "0.9.1-1",
      "Severity": "low"
    },
    {
      "Original": "NOTE: https://github.com/uriparser/uriparser/commit/cef25028de5ff872c2e1f0a6c562eb3ea9ecbce4",
      "Line": 303251,
      "Type": "NOTE",
      "Description": "https://github.com/uriparser/uriparser/commit/cef25028de5ff872c2e1f0a6c562eb3ea9ecbce4"
    }
  ]
}