{
  "Header": {
    "Original": "CVE-2019-13565 (An issue was discovered in OpenLDAP 2.x before 2.4.48. When using SASL ...)",
    "Line": 282018,
    "ID": "CVE-2019-13565",
    "Description": "(An issue was discovered in OpenLDAP 2.x before 2.4.48. When using SASL ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-1891-1}",
      "Line": 282019,
      "Type": "xref",
      "Bugs": [
        "DLA-1891-1"
      ]
    },
    {
      "Original": "- openldap 2.4.48+dfsg-1 (low; bug #932998)",
      "Line": 282020,
      "Type": "package",
      "Package": "openldap",
      "Kind": "fixed",
      "Version": "2.4.48+dfsg-1",
      "Severity": "low",
      "BugNo": 932998
    },
    {
      "Original": "[buster] - openldap 2.4.47+dfsg-3+deb10u1",
      "Line": 282021,
      "Type": "package",
      "Release": "buster",
      "Package": "openldap",
      "Kind": "fixed",
      "Version": "2.4.47+dfsg-3+deb10u1"
    },
    {
      "Original": "[stretch] - openldap 2.4.44+dfsg-5+deb9u3",
      "Line": 282022,
      "Type": "package",
      "Release": "stretch",
      "Package": "openldap",
      "Kind": "fixed",
      "Version": "2.4.44+dfsg-5+deb9u3"
    },
    {
      "Original": "NOTE: https://openldap.org/its/?findid=9052",
      "Line": 282023,
      "Type": "NOTE",
      "Description": "https://openldap.org/its/?findid=9052"
    }
  ]
}